# The Docker image that will be used to build your app
image: node:lts

before_script:
  - npm install

pages:
  script:
    - npm run build
  artifacts:
    paths:
      - public
  only:
    - main  # Adjust this to match your main branch name